#pragma once
#include "windows.h"

#define IOCTL_PROCESS_PROTECT_BY_PID CTL_CODE(0x8000, 0x800, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_PROCESS_UNPROTECT_BY_PID CTL_CODE(0x8000, 0x801, METHOD_BUFFERED, FILE_ANY_ACCESS)
//这个不需要穿参数，不需要对用户内存进行访问处理
#define IOCTL_PROCESS_PROTECT_CLEAR CTL_CODE(0x8000, 0x802, METHOD_NEITHER, FILE_ANY_ACCESS)

